const employees = [
  {
    employeeId: 4,
    chairId: 3,
    name: "Aditya ",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 5,
    chairId: 2,
    name: "Siddharth ",
    position: "Developer",
    team: "Backend",
    project: "API Development",
  },
  {
    employeeId: 6,
    chairId: 1,
    name: "Sandeep ",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },

  {
    employeeId: 2,
    chairId: 3,
    name: "Krish ",
    position: " Developer",
    team: "Android ",
    project: " App Redesign",
  },
  {
    employeeId: 1,
    chairId: 1,
    name: "Moh Faizan ",
    position: " Developer",
    team: "Web Developer",
    project: "API Development",
  },
  {
    employeeId: 3,
    chairId: 2,
    name: "Shubhang ",
    position: " Developer",
    team: "Backend",
    project: "API Development",
  },
  {
    employeeId: 7,
    chairId: 4,
    name: "Mayank ",
    position: "Developer",
    team: "Backend",
    project: "API Development",
  },
  {
    employeeId: 8,
    chairId: 3,
    name: "Kishan ",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 9,
    chairId: 1,
    name: "Raja",
    position: "Developer",
    team: "Backend",
    project: "API Development",
  },
  {
    employeeId: 10,
    chairId: 2,
    name: "Nikhil",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 11,
    chairId: 3,
    name: "Rohan ",
    position: "Developer",
    team: "Backend",
    project: "API Development",
  },
  {
    employeeId: 12,
    chairId: 4,
    name: "Mritunjay",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 13,
    chairId: 1,
    name: "Mritunjay",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 14,
    chairId: 2,
    name: "Vikas ",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 15,
    chairId: 4,
    name: "Om",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 16,
    chairId: 3,
    name: "Mritunjay",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 17,
    chairId: 4,
    name: "Mritunjay",
    position: "Designer",
    team: "UI/UX",
    project: "App Redesign",
  },
  {
    employeeId: 18,
    chairId: 4,
    name: "Rajshree",
    position: "Developer",
    team: "Backend",
    project: "API Development",
  },
];
export default employees;
